### DISCUSSION TITLE
How to call an API from JavaScript

### DISCUSSION THREAD

**Discussion by hlaueriksson** [microsoft/aspire#1035] [Q&A] [answered]
I have two projects with .NET Aspire Orchestrator Support:
- `api`
- `htmx`

The `htmx` project is a ASP.NET Core Web App with static HTML.

From the static HTML I want to make a GET request to for example `/api/hello` via JavaScript [(htmx)](https://htmx.org/).

How can I make enable the orchestration to the API in the JavaScript?

With `Tye` I solved this with an [ingress](https://github.com/dotnet/tye/blob/main/docs/recipes/ingress.md).

**Comment by davidfowl** [comment]
Can you show what you were doing with tye?

**Comment by hlaueriksson** [comment]
I have a sample solution with HTMX + Minimal API:
- https://github.com/hlaueriksson/Markupolation/tree/main/samples#htmx--api

`tye-htmx.yaml`:

```yml
name: markupolation
services:
- name: markupolation-sample-api
  project: Markupolation.Sample.Api/Markupolation.Sample.Api.csproj
  bindings:
  - port: 5000
    protocol: https
- name: markupolation-sample-htmx
  project: Markupolation.Sample.Htmx/Markupolation.Sample.Htmx.csproj
  bindings:
  - port: 5001
    protocol: https
ingress:
  - name: ingress
    bindings:
      - port: 8080
        protocol: https
    rules:
    - path: /api
      service: markupolation-sample-api
    - service: markupolation-sample-htmx
```

`index.html`:

```html
<article class="content px-4">
    <!-- Lazy Loading -->
    <div hx-get="/api/hello" hx-trigger="load"></div>
</article>
```

- This makes a GET request to the API with [htmx](https://htmx.org/)

When browsing the site via the ingress, it works like a charm:

- `https://localhost:8080/`
