### DISCUSSION TITLE
Question Regarding Port Issue With Container Resource

### DISCUSSION THREAD

**Discussion by josephaw1022** [microsoft/aspire#1894] [Q&A] [answered]
Ok so I am currently trying to run this program.cs file in my app host project 

```csharp

var builder = DistributedApplication.CreateBuilder(args);


var minioContainer = builder.AddContainer("minio", "minio/minio")
    .WithServiceBinding(containerPort: 9000, name: "minio-container-port")
    .WithServiceBinding(containerPort: 9001, name: "minio-console-port")
    .WithEnvironment("MINIO_ROOT_USER", "minio")
    .WithEnvironment("MINIO_ROOT_PASSWORD", "RunningZebraMan32332#")
    .WithArgs("server", "/data", "--console-address", "\"9001\"");

builder.AddProject<Projects.ApiWithS3>("apiwiths3");


builder.AddProject<Projects.ApiWithMinio>("apiwithminio");


builder.Build().Run();

```

and I am getting this error when I run the app host 

![image](https://github.com/dotnet/aspire/assets/47674962/e70b2c28-8d85-4282-aaac-7565d611bdc7)

When I run the minio container with no admin port, it works just fine. 

```csharp 

var builder = DistributedApplication.CreateBuilder(args);


var minioContainer = builder.AddContainer("minio", "minio/minio")
    .WithServiceBinding(containerPort: 9000, name: "minio-container-port")
    .WithEnvironment("MINIO_ROOT_USER", "minio")
    .WithEnvironment("MINIO_ROOT_PASSWORD", "RunningZebraMan32332#")
    .WithArgs("server", "/data");

builder.AddProject<Projects.ApiWithS3>("apiwiths3");


builder.AddProject<Projects.ApiWithMinio>("apiwithminio");


builder.Build().Run();

```

and I get this 

![image](https://github.com/dotnet/aspire/assets/47674962/fcf8f922-f51a-441c-b630-885e651ac02e)

### Note

The command for the container doesn't seem to be the issue as it works in this compose file 

```yaml
# ... rest of file 
  # Minio service
  minio:
    image: minio/minio
    ports:
      - '9002:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    restart: unless-stopped
    env_file: './config/minio.env'
    command: server --console-address ":9001" /data

```

## My Question 

How do I get the first command to work with the console endpoint? Not sure what I need to do to make the first example I showed work.
