### DISCUSSION TITLE
Github Actions Workflow for Secret Parameters

### DISCUSSION THREAD

**Discussion by vicperdana** [microsoft/aspire#4083] [Q&A] [answered]
Given these parameters defined in the `AppHost` project, we'll be asked the values when running `azd up`.  How do we pass these into GitHub Actions Workflow?

The [sample](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/azure/aca-deployment-github-actions?tabs=windows%2Cvisual-studio&pivots=github-actions#add-the-github-actions-workflow-file) uses `azd provision` but I could not find any [reference](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference#azd-provision) where I could pass in these params. 

```csharp
var chatModelId = builder.AddParameter("chatModelId", secret: true);
var chatApiKey = builder.AddParameter("chatApiKey", secret: true);
```

**Comment by davidfowl** [comment]
https://learn.microsoft.com/en-us/dotnet/aspire/whats-new/preview-4#prompting-for-parameters

cc @vhvb1989

**Comment by vhvb1989** [comment]
@vicperdana 

Update the sample definition to look like:

```yaml
on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v0.1.0

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Log in with Azure (Federated Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh

      - name: Log in with Azure (Client Credentials)
        if: ${{ env.AZURE_CREDENTIALS != '' }}
        run: |
          $info = $Env:AZURE_CREDENTIALS | ConvertFrom-Json -AsHashtable;
          Write-Host "::add-mask::$($info.clientSecret)"

          azd auth login `
            --client-id "$($info.clientId)" `
            --client-secret "$($info.clientSecret)" `
            --tenant-id "$($info.tenantId)"
        shell: pwsh

      - name: Provision Infrastructure
        run: azd provision --no-prompt
        env:
          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}

      - name: Deploy Application
        run: azd deploy --no-prompt
```

The only change is the addition of env variable to the `azd provision` step:

>         env:
>          AZD_INITIAL_ENVIRONMENT_CONFIG: ${{ secrets.AZD_INITIAL_ENVIRONMENT_CONFIG }}

Then you can run `azd pipeline config` and azd will set `secrets.AZD_INITIAL_ENVIRONMENT_CONFIG` with the values you entered for the secret params and when running on CI, those values will be used.

If you want to pick new values (like for a different environment), you can run `azd env new prod` and then `azd pipeline config`.
azd will ask for new values and set them to the github action.
