### DISCUSSION TITLE
OTLP Logs Endpoint - Missing clear documentation

### DISCUSSION THREAD

**Discussion by dominiclapointe** [microsoft/aspire#4326] [Q&A]
Hi all,

I have a classic Aspire solution (v 8.0.1). I have a few APIs and its working just great. 

I am now trying to send openTelemetry logs from a MAUI application to the dashboard by using a CustomExporter: BaseExpoter<LogRecord> as i think / know that MAUI is not supported by Aspire out of the box. 

I am ok not having service discovery and other features for that project, but would really like being able to redirect logs, metrics and traces to the same place than my APIs will be.

From what i understand, we can call the LogsService either using Http or Grpc from what i understand from this code in logs_service_http.yaml :
```
This is an API configuration to generate an HTTP/JSON -> gRPC gateway for the
OpenTelemetry service using github.com/grpc-ecosystem/grpc-gateway.
type: google.api.Service
config_version: 3
http:
 rules:
 - selector: opentelemetry.proto.collector.logs.v1.LogsService.Export
   post: /v1/logs
   body: "*"
```

To get started, im trying to be able to do a call using Postman but =>

1. When i try an http call, it throw the error socket Socket hang up
![image](https://github.com/dotnet/aspire/assets/47004797/471db28f-fd47-43cd-ad4e-a1b4b80e3f6f)

2. When i try GRPC, using the logs_service.proto as definition, i get an error 16 UNAUTHENTICATED, even tough i send the token :
![image](https://github.com/dotnet/aspire/assets/47004797/603c7229-361b-40b0-9042-1174d9d26d19)

Here is the launchSettings.json of my AppHost :
![image](https://github.com/dotnet/aspire/assets/47004797/e2420cd2-a41c-44ae-9fc3-815cef78ead2)

Ive read somewhere that some of those env_var might not be taking into consideration when running the full aspire but only for the standalone dashboard. I know the OTLP is listening on the specified port (6666) so this config is working. As for the API Key, i tried with mine (123456) but also with the random key generated by the dashboard. None seems to works 
![image](https://github.com/dotnet/aspire/assets/47004797/da6973b4-1cef-40d3-8118-ec563be26150)

Am i missing something or is it really just not meant to be call by a 'not aspire' project / app?

Any direction would be much appreciated and i guess some documentation on this use case could be more than welcome for the community as i would expect i am not the only one willing to integrate 'non aspire' application into an 'aspire solution'.

Thank you
