### DISCUSSION TITLE
Error Thrown in Aspire Azure Devops Deploy (but Locally Works)

### DISCUSSION THREAD

**Discussion by Mike-E-angelo** [microsoft/aspire#5507] [Q&A] [answered]
Hello all,

I have been able to use `azd up` and `azd deploy` on my local machine without any issues, deploying resources to Azure.  Everything works great there and it's been pretty impressive to use.

Now I have taken the next step and am attempting to run it as an Azure DevOps pipeline and while provisioning works it is throwing during `deploy`:

```
D:\a\1\s>azd deploy --no-prompt 
Analyzing Aspire Application (this might take a moment...)

Deploying services (azd deploy)

Deploying service administration
Deploying service administration (Logging in to registry)
Deploying service administration (Pushing container image)
  (x) Failed: Deploying service administration

{"config":{"ExposedPorts":{"8080/tcp":{}},"Labels":{"org.opencontainers.image.created":"2024-08-31T06:55:16.2248502Z","org.opencontainers.artifact.created":"2024-08-31T06:55:16.2248502Z","org.opencontainers.image.authors":"Project.Web.Administration","org.opencontainers.image.version":"0.0.0-ge3daf49b93","org.opencontainers.image.base.name":"mcr.microsoft.com/dotnet/aspnet:8.0","net.dot.runtime.majorminor":"8.0","net.dot.sdk.version":"8.0.401","org.opencontainers.image.base.digest":"sha256:4e4516be86bb7bd21e61717479c22567b6455a87344fe62dbf9f253262405807"},"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","APP_UID=1654","ASPNETCORE_HTTP_PORTS=8080","DOTNET_RUNNING_IN_CONTAINER=true","DOTNET_VERSION=8.0.8","ASPNET_VERSION=8.0.8"],"WorkingDir":"/app","Entrypoint":["dotnet","Project.Web.Administration.dll"],"User":"1654"},"created":"2024-08-31T06:55:36.1258592Z","rootfs":{"type":"layers","diff_ids":["sha256:9853575bc4f955c5892dd64187538a6cd02dba6968eba9201854876a7a257034","sha256:f553d2208193955aac6e75ee89b840ffde4f89cc66975118598dc1f2b2c7232c","sha256:e74c54caa59e298fb9bbe3257563dd778f6caf5d3041fa7addfa85e363f93995","sha256:9102fd62231f737a0088d688887b98a67ab7440c862026644eaf82602d789cff","sha256:8b270f8da82400aaacc68dca14760718a0d9d3ee04a7d716041215b51a01c556","sha256:4b5f9ea48c8a5fff5c045dab07bdf2853c292f61de29548300795125f8d86a31","sha256:fb8e690456584c009f8903bdf6432cc200e58fb064a26463f67aacc40d5f9215"]},"architecture":"amd64","os":"linux","history":[{"created":"2024-08-13T00:20:20.1241770Z","created_by":"/bin/sh -c #(nop) ADD file:3d9897cfe027ecc7cbdb16e74a676ed143725ea2d08dbb0dde23309e041de0f3 in / "},{"created":"2024-08-13T00:20:20.4412919Z","created_by":"/bin/sh -c #(nop)  CMD [\u0022bash\u0022]","empty_layer":true},{"comment":"buildkit.dockerfile.v0","created":"2024-08-13T13:45:05.5877641Z","created_by":"ENV APP_UID=1654 ASPNETCORE_HTTP_PORTS=8080 DOTNET_RUNNING_IN_CONTAINER=true","empty_layer":true},{"comment":"buildkit.dockerfile.v0","created":"2024-08-13T13:45:05.5877641Z","created_by":"RUN /bin/sh -c apt-get update     \u0026\u0026 apt-get install -y --no-install-recommends         ca-certificates                 libc6         libgcc-s1         libicu72         libssl3         libstdc\u002B\u002B6         tzdata         zlib1g     \u0026\u0026 rm -rf /var/lib/apt/lists/* # buildkit"},{"comment":"buildkit.dockerfile.v0","created":"2024-08-13T13:45:07.0697036Z","created_by":"RUN /bin/sh -c groupadd         --gid=$APP_UID         app     \u0026\u0026 useradd -l         --uid=$APP_UID         --gid=$APP_UID         --create-home         app # buildkit"},{"comment":"buildkit.dockerfile.v0","created":"2024-08-13T13:45:14.5249536Z","created_by":"ENV DOTNET_VERSION=8.0.8","empty_layer":true},{"comment":"buildkit.dockerfile.v0","created":"2024-08-13T13:45:14.5249536Z","created_by":"COPY /dotnet /usr/share/dotnet # buildkit"},{"comment":"buildkit.dockerfile.v0","created":"2024-08-13T13:45:15.6336548Z","created_by":"RUN /bin/sh -c ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet # buildkit"},{"comment":"buildkit.dockerfile.v0","created":"2024-08-13T13:45:21.8780669Z","created_by":"ENV ASPNET_VERSION=8.0.8","empty_layer":true},{"comment":"buildkit.dockerfile.v0","created":"2024-08-13T13:45:21.8780669Z","created_by":"COPY /shared/Microsoft.AspNetCore.App /usr/share/dotnet/shared/Microsoft.AspNetCore.App # buildkit"},{"author":".NET SDK","created":"2024-08-31T06:55:36.1258230Z","created_by":".NET SDK Container Tooling, version 8.0.401-servicing.24408.18\u002B41b13414c4a35aac269719f7281cf74c9c9aae31"}]}
'

Ensure project 'D:\a\1\s\Project.Web.Administration\Project.Web.Administration.csproj' is enabled for container support and try again. To enable SDK container support, set the 'EnableSdkContainerSupport' property to true in your project file

##[error]Script failed with exit code: 1

```

This happens on both Windows and Ubuntu agent images, using SDK 8.0.401 on Aspire 8.2.0.

As it works perfect on my local machine I am unclear on what could be the issue here.  I would greatly appreciate any pointers/context towards resolving this.  Thank you for your assistance and all your efforts out there.

**Comment by davidfowl** [comment]
cc @baronfel

**Reply by Mike-E-angelo** [reply]
Please let me know if I should create an issue to track. 👍

**Reply by baronfel** [reply]
Can you get an https://aka.ms/binlog and attach it here if you're comfortable and/or create a VS dev community ticket and link the ticket here?

**Reply by Mike-E-angelo** [reply]
Sure thing @baronfel I have attached that here: https://developercommunity.visualstudio.com/t/Providing-BinLog-as-Requested/10742031

Please let me know if there is any further information to provide and I will assist.

**Reply by baronfel** [reply]
@Mike-E-angelo Thanks for creating the ticket! I don't see the binlog attached to the ticket though, can you double-check?

**Reply by Mike-E-angelo** [reply]
I see it as uploaded @baronfel.  Sometimes it takes a bit for the actual file to be available:

![image](https://github.com/user-attachments/assets/8cb82649-eae0-484a-8bf6-c23b6735ae1c)

Please let me know if I should I try again.

**Reply by baronfel** [reply]
Hey @Mike-E-angelo - I see the binlog now but it doesn't show this failure at all. Are you sure this is a failing binlog? If you need to get a binlog from `azd` you won't be able to use `-bl` directly - in that case you'll need to set the `MSBUILDDEBUGENGINE=1` environment variable in the shell before you call `azd deploy`, which should result in a binlog file called `msbuild.binlog` getting created.

**Reply by Mike-E-angelo** [reply]
Ah!  I completely misunderstood your goal @baronfel apologies.  Please be aware that this is occurring during Azure DevOps build, and it is unclear how to get the file after compilation.  I do have a self-hosted agent, but this is not possible due to another issue I am facing here: https://github.com/Azure/azure-dev/issues/4282

I am open to any suggestions on how to get this file for you considering the circumstances. 🤔

**Reply by baronfel** [reply]
Generally for builds happening in CI/CD, you'll create the binlog during a certain step but you'll need some kind of explicit 'upload artifact's step that happens right after to capture any generated files you want to save (like this binlog). This doc might help you get the binlog from your pipeline: https://learn.microsoft.com/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops

**Reply by Mike-E-angelo** [reply]
Alright @baronfel let's try again 😁🤞 https://developercommunity.visualstudio.com/t/Providing-BinLog-as-Requested/10742031#T-N10742122

**Reply by baronfel** [reply]
I took a look at the new binlog (thanks!) and that one is from Visual Studio, not the `azd` command that's erroring. I need a binlog from that failing command to see what's going wrong.

**Reply by Mike-E-angelo** [reply]
We are definitely in uncharted territory for me now.  It might be more effective to start with what I have:

```
  - task: AzureCLI@2
    displayName: Deploy Application
    inputs:
      azureSubscription: azconnection
      scriptType: pwsh
      scriptLocation: inlineScript
      keepAzSessionActive: true
      inlineScript: |
        azd deploy --no-prompt --all
      workingDirectory: $(SOLUTION_NAME).AppHost
    continueOnError: true
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
      MSBUILDDEBUGENGINE: 1
  - task: CopyFiles@2
    displayName: 'Copy binlogs'
    inputs:
      contents: '**/*.binlog'
      targetFolder: '$(Build.ArtifactStagingDirectory)/logs'
  - publish: '$(Build.ArtifactStagingDirectory)/logs'
    displayName: 'Publish logs'
    artifact: drop
```

(Note that all binlogs no matter where they are under the root should be copied)

Tell me what to fix and I will do so. :)

**Reply by baronfel** [reply]
That looks reasonable to me, but the logs you uploaded most recently are VS logs, not logs that I'd expect from azd calling MSBuild.

**Reply by Mike-E-angelo** [reply]
The mystery deepens here then as this is what was output in the ADO task log:

```
Copying D:\a\1\s\<Project>.AppHost\MSBuild_Logs\CentralNode_dotnet_PID=6820_x64_BuildManager_Default.binlog to D:\a\1\a\logs\<Project>.AppHost\MSBuild_Logs\CentralNode_dotnet_PID=6820_x64_BuildManager_Default.binlog
```
🤔

Maybe we'll wait until the `azd` team fixes the permissions issue on the `azd` installer and I can try this on my self-hosted agent where I have more control?  I'm open to other suggestions in the meantime.

**Reply by baronfel** [reply]
We need help from the azd team IMO. The json object you see is the information that the .NET SDK generated from publishing your container successfully, and azd is supposed to read that output (specifically the 'config' property) before continuing on. From what I can see this is working correctly, so we need someone from that team to chime in.

**Reply by davidfowl** [reply]
cc @vhvb1989

**Reply by vhvb1989** [reply]
Can you share the entire Azdo pipeline definition @Mike-E-angelo ?

And, about 
> Maybe we'll wait until the azd team fixes the permissions issue on the azd installer

You can directly run the install script from Ci/CD (w/o the install-azd step). For example, if your CI/CD is running linux:
```
- task: Bash@3
    displayName: Install azd
    inputs:
      targetType: 'inline'
      script: |
        curl -fsSL https://aka.ms/install-azd.sh | bash
```

The benefit of `task: setup-azd@0 ` is just to handle cross-os installation, so you can change your pipeline from Win to Lin and the step works.  But you can directly use the install script for Lin or Win directly from your self-hosted agent.

Another question,, did you use `azd pipeline config` to set up the pipeline?  or are you setting it up manually?  You might wat to see this: https://learn.microsoft.com/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=azdo#advanced-features

**Reply by Mike-E-angelo** [reply]
Thank you very much for your time and assistance @vhvb1989 it is appreciated. 

> Can you share the entire Azdo pipeline definition

Sure thing:

```
trigger:
  - deploy/testing

pool:
  vmImage: windows-latest

steps:
  - checkout: self
    fetchDepth: 0
    clean: false
    submodules: true
  # setup-azd@0 needs to be manually installed in your organization
  # if you can't install it, you can use the below bash script to install azd
  # and remove this step
  - task: setup-azd@0
    displayName: Install azd
  - task: UseDotNet@2
    displayName: Install .NET SDK
    inputs:
      packageType: 'sdk' # 'runtime' | 'sdk'. Package to install. Default: sdk.
    #useGlobalJson: false # boolean. Optional. Use when packageType = sdk. Use global json. Default: false.
    #workingDirectory: # string. Optional. Use when useGlobalJson = true. Working Directory.
      version: '8.0.401'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet workload'
    inputs:
      command: custom
      custom: 'workload '
      arguments: 'restore'
  # azd delegate auth to az to use service connection with AzureCLI@2
  - pwsh: |
      azd config set auth.useAzCliAuth "true"
    displayName: Configure AZD to Use AZ CLI Authentication.
  - bash: |
      # Extract the solution name from the .sln file
      SOLUTION_NAME=$(ls *.sln | sed 's/\.sln$//')
      echo "Solution Name: $SOLUTION_NAME"
      echo "##vso[task.setvariable variable=SOLUTION_NAME]$SOLUTION_NAME"
    displayName: Extract Solution Name
  - task: AzureCLI@2
    displayName: Provision Infrastructure
    inputs:
      azureSubscription: azconnection
      scriptType: pwsh
      scriptLocation: inlineScript
      keepAzSessionActive: true
      inlineScript: |
        azd provision --no-prompt
        azd env refresh --no-prompt
      workingDirectory: $(SOLUTION_NAME).AppHost
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
      AZD_INITIAL_ENVIRONMENT_CONFIG: $(AZD_INITIAL_ENVIRONMENT_CONFIG)

  - task: AzureCLI@2
    displayName: Deploy Application
    inputs:
      azureSubscription: azconnection
      scriptType: pwsh
      scriptLocation: inlineScript
      keepAzSessionActive: true
      inlineScript: |
        azd deploy --no-prompt --all
      workingDirectory: $(SOLUTION_NAME).AppHost
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
```

> You can directly run the install script from Ci/CD

Can you please verify if this will avoid the issue I am encountering here: https://github.com/Azure/azure-dev/issues/4282

> Another question,, did you use azd pipeline config to set up the pipeline? 

This is a good question.  I based it on the following blog post which seems to have done this:
https://agramont.net/blog/devops-intro-deploy-net-aspire-azure-github-actions/

EDIT: Yes, I can confirm that I have used `azd pipeline config` to create/connect this pipeline.

I am certainly open to further suggestions and guidance on how to diagnose this issue. 👍
