### DISCUSSION TITLE
getting an error on aspire deployment - ManagedEnvironmentStorageShareNameInvalidRequest

### DISCUSSION THREAD

**Discussion by markat1** [microsoft/aspire#5831] [Q&A] [answered]
I'm trying to publish my aspire application to azure, but I get an error:

`ManagedEnvironmentStorageShareNameInvalidRequest: Invalid request body for managed environment storage 'app-firstprojecttowar'. 'properties.azureFile.shareName' must be proivded when setting Azure File Share Storage. The length must be at least 3 characters and no more than 63 characters.
`
before I published:

1. I created a manifest with
```
dotnet run --project AspireApp.AppHost\AspireApp.AppHost.csproj `
    -- `
    --publisher manifest `
    --output-path ../aspire-manifest.json 
```
2. then I used publish inside visual studio

![image](https://github.com/user-attachments/assets/6c793eb7-5f39-46a5-9011-1cf0db88dea8)

3. received the error during publish:

![image](https://github.com/user-attachments/assets/e5ec8dfa-782c-42ca-80aa-e6f39f5dbc31)

**Comment by davidfowl** [comment]
You don’t need to create the manifest. The toolchain does that on your behalf. 

As for the error, go to the command line and run azd infra synth in the app host folder. That will show the details of the generated bicep that we can analyze

**Reply by markat1** [reply]
@davidfowl  - okay I ran `azd infra synth` - does it produce any file? don't seem to say that in command line.

![image](https://github.com/user-attachments/assets/ccca3a74-5e9c-47c5-97e1-4d14ce1566a2)

**Reply by markat1** [reply]
@davidfowl  - oh it did create some files! okay so any idea what I should be looking for?

![image](https://github.com/user-attachments/assets/f7fd6b6c-7b2e-4462-a3be-799838a7dad4)

**Reply by markat1** [reply]
oh okay - might be that volume name is too long. I will try see if I can change it.

For some reason it takes the name twice?

![image](https://github.com/user-attachments/assets/47a9b11b-ec50-4c24-a91f-6beaac961550)

**Reply by markat1** [reply]
hmm okay - made the volume name smaller, but still same error :(

**Reply by markat1** [reply]
Here's the file that I suspect has the error - I replaced the actual volume name with "examplename" and portname to 12344
```
api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: 12344
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    volumes:
      - name: examplename-examplename
        storageType: AzureFile
        storageName: {{ .Env.SERVICE_EXAMPLENAME_VOLUME_EXAMPLE_NAME }} 
    containers:
      - image: {{ .Image }}
        name: examplename
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
        volumeMounts:
          - volumeName: examplename-examplename
            mountPath: /root/.test
    scale:
      minReplicas: 1
tags:
  azd-service-name: examplename
  aspire-resource-name: examplename
```
