### DISCUSSION TITLE
Can't bind port during E2E tests run

### DISCUSSION THREAD

**Discussion by atlass-dev** [microsoft/aspire#6843] [Q&A] [answered]
I have a container for SMTP server:
```
builder.AddContainer("Mail", "mailhog/mailhog")
    .WithEndpoint(port: 8025, targetPort: 8025, name: "web", scheme: "http")
    .WithEndpoint(port: 1025, targetPort: 1025, name: "smtp");
```

When I run the `AppHost`, I'm able to reach this application on `localhost:8025`, as well as on host port generated by Aspire.

However, when I run E2E tests, it's not possible to reach `localhost:8025` - only the host port is applicable. As I noticed the same is for the other resources, e.g. Postgres, but there's a service discrovery doing their job, so it won't interrupt anything.

**How to set static port in both cases?**

Actual pod manifests are the same:
For plain `AppHost` run:
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-11-29T05:42:08Z"
  labels:
    app: Mail-wcugmvcn-pod
  name: Mail-wcugmvcn-pod
spec:
  containers:
  - image: docker.io/mailhog/mailhog:latest
    name: Mail-wcugmvcn
    ports:
    - containerPort: 1025
      hostIP: 127.0.0.1
      hostPort: 45178
    - containerPort: 8025
      hostIP: 127.0.0.1
      hostPort: 45292
    securityContext: {}
```

For E2E tests run:
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-11-29T05:43:16Z"
  labels:
    app: Mail-btuapnae-505db452-pod
  name: Mail-btuapnae-505db452-pod
spec:
  containers:
  - image: docker.io/mailhog/mailhog:latest
    name: Mail-btuapnae-505db452
    ports:
    - containerPort: 1025
      hostIP: 127.0.0.1
      hostPort: 44776
    - containerPort: 8025
      hostIP: 127.0.0.1
      hostPort: 46114
    securityContext: {}
```
