### DISCUSSION TITLE
No reference in values.yaml to referenced project.

### DISCUSSION THREAD

**Discussion by erikhermansson79** [microsoft/aspire#9856] [General]
Hi,

I think the values.yaml file is missing some values.

I made a simple solution to show my issue. This is my AppHost.cs (Aspire 9.3.1):

```csharp
var builder = DistributedApplication.CreateBuilder(args);
builder.AddKubernetesEnvironment("kubernetes");

var backend = builder.AddProject<Projects.BackEnd>("backend");

builder.AddProject<Projects.FrontEnd>("frontend")
    .WithReference(backend);

builder.Build().Run();
```

The ConfigMap for the FrontEnd project looks like this:

```yaml
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "frontend-config"
  labels:
    app: "aspire"
    component: "frontend"
data:
  ASPNETCORE_URLS: "{{ .Values.config.frontend.ASPNETCORE_URLS }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.frontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.frontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.frontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.frontend.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.frontend.HTTP_PORTS }}"
  services__backend__http__0: "{{ .Values.config.frontend.services__backend__http__0 }}"
  services__backend__https__0: "{{ .Values.config.frontend.services__backend__https__0 }}"
```

`services__backend__http__0` and `services__backend__https__0` are both referring to config, not secrets, so I assumed they would exist in the values.yaml file, but my values.yaml looks like this:

```yaml
parameters:
  backend:
    port_http: "8080"
    port_https: "8080"
    backend_image: "backend:latest"
  frontend:
    port_http: "8080"
    port_https: "8080"
    frontend_image: "frontend:latest"
secrets: {}
config:
  backend:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  frontend:
    ASPNETCORE_URLS: "http://+:$8080"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"

```
