### DISCUSSION TITLE
How would you configure the platform architecture using the `PublishAsDockerComposeService` extension?

### DISCUSSION THREAD

**Discussion by Clink50** [microsoft/aspire#9960] [Q&A] [answered]
I'm attempting to dockerize my .NET Aspire application and send it to my raspberry pi to run as a web server. The architecture for the pi is linux/arm64, so I need to configure the platform in the docker compose to build the image correctly, but I'm not seeing an option for "platform" in the Service class.

**Comment by engineering87** [comment]
Hello @Clink50,
Aspire itself doesn’t seem to provide a first-class API for setting the platform per service.
You can try this workaround, using an override raw yml to specify the platform.

```yaml
services:
  my-service:
    image: myapp:latest
    platform: linux/arm64
```
